/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author Alunos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jIncluirAgencia = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jIncluirCliMenu = new javax.swing.JMenuItem();
        jAlterarCliMenu = new javax.swing.JMenuItem();
        jExcluirCliMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jIncluirHist = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jIncluirCCMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jIncluirUser = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jIncluirMov = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jMenu6.setText("Agências");

        jIncluirAgencia.setText("Incluir");
        jIncluirAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncluirAgenciaActionPerformed(evt);
            }
        });
        jMenu6.add(jIncluirAgencia);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("Clientes");

        jIncluirCliMenu.setText("Incluir");
        jIncluirCliMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncluirCliMenuActionPerformed(evt);
            }
        });
        jMenu3.add(jIncluirCliMenu);

        jAlterarCliMenu.setText("Alterar");
        jAlterarCliMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarCliMenuActionPerformed(evt);
            }
        });
        jMenu3.add(jAlterarCliMenu);

        jExcluirCliMenu.setText("Excluir");
        jExcluirCliMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirCliMenuActionPerformed(evt);
            }
        });
        jMenu3.add(jExcluirCliMenu);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Históricos");

        jIncluirHist.setText("Incluir");
        jIncluirHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncluirHistActionPerformed(evt);
            }
        });
        jMenu2.add(jIncluirHist);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Conta Corrente");

        jIncluirCCMenu.setText("Incluir");
        jIncluirCCMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncluirCCMenuActionPerformed(evt);
            }
        });
        jMenu4.add(jIncluirCCMenu);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Usuário");

        jIncluirUser.setText("Incluir");
        jIncluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncluirUserActionPerformed(evt);
            }
        });
        jMenu1.add(jIncluirUser);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Movimentação");

        jIncluirMov.setText("Incluir");
        jIncluirMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncluirMovActionPerformed(evt);
            }
        });
        jMenu5.add(jIncluirMov);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIncluirCliMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncluirCliMenuActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        CadastroClientes acessoCliente = new CadastroClientes(operacao);
        acessoCliente.setVisible(true);
    }//GEN-LAST:event_jIncluirCliMenuActionPerformed

    private void jAlterarCliMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarCliMenuActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        CadastroClientes cadCliente = new CadastroClientes(operacao);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_jAlterarCliMenuActionPerformed

    private void jExcluirCliMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirCliMenuActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        CadastroClientes cadCliente = new CadastroClientes(operacao);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_jExcluirCliMenuActionPerformed

    private void jIncluirCCMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncluirCCMenuActionPerformed
        // TODO add your handling code here:
        String operacao = "Inclluir";
        CadastroCC cadCC = new CadastroCC(operacao);
        cadCC.setVisible(true);
    }//GEN-LAST:event_jIncluirCCMenuActionPerformed

    private void jIncluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncluirUserActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        CadastroUser cadUser = new CadastroUser(operacao);
        cadUser.setVisible(true);
    }//GEN-LAST:event_jIncluirUserActionPerformed

    private void jIncluirAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncluirAgenciaActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        CadastroAgencia cadAgencia = new CadastroAgencia(operacao);
        cadAgencia.setVisible(true);
    }//GEN-LAST:event_jIncluirAgenciaActionPerformed

    private void jIncluirHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncluirHistActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        CadastroHist cadHist = new CadastroHist(operacao);
        cadHist.setVisible(true);
    }//GEN-LAST:event_jIncluirHistActionPerformed

    private void jIncluirMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncluirMovActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        CadastroMov cadMov = new CadastroMov(operacao);
        cadMov.setVisible(true);
    }//GEN-LAST:event_jIncluirMovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAlterarCliMenu;
    private javax.swing.JMenuItem jExcluirCliMenu;
    private javax.swing.JMenuItem jIncluirAgencia;
    private javax.swing.JMenuItem jIncluirCCMenu;
    private javax.swing.JMenuItem jIncluirCliMenu;
    private javax.swing.JMenuItem jIncluirHist;
    private javax.swing.JMenuItem jIncluirMov;
    private javax.swing.JMenuItem jIncluirUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
