ano_de_nascimento = int(input("Digite o ano de nascimento: "))
ano_atual = int(input("Digite o ano em que estamos: "))
print("Você tem:", (ano_atual - ano_de_nascimento), "anos")
print("Você tem:", (ano_atual - ano_de_nascimento) * 12, "meses")
print("Você tem:", (ano_atual - ano_de_nascimento) * 365, "dias")
print("Você tem:", (ano_atual - ano_de_nascimento) * 53, "semanas")
